### ISSUE TITLE
Aether crashes with StationAPI

### ISSUE THREAD

**Issue by istupidgirl** [BetterThanUpdates/apron#51]
## Description
I want to have an instance with Aether & MojangFix (Station API Edition). I can use Apron to run Babric with Aether, but when I install StationAPI for MojangFix it crashes. Other mods such as BuildCraft & IndustrialCraft seem to be working fine though. 

## Mods + Version info:
 - Apron version: `2.0.1`
 - Aether version: `1.0.2`
 - StationAPI version: `2.0-alpha.1.1`

## Crash Report

<details>

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at modloader.ModLoader.addInternalMod(ModLoader.java:323)
	at modloader.ModLoader.readFromModFolder(ModLoader.java:1270)
	at modloader.ModLoader.init(ModLoader.java:790)
	at modloader.ModLoader.AddAllRenderers(ModLoader.java:222)
	at net.minecraft.class_578.handler$zck000$apron-impl$modloader$ctr(class_578.java:526)
	at net.minecraft.class_578.<init>(class_578.java:75)
	at net.minecraft.class_578.<clinit>(class_578.java:26)
	at net.minecraft.client.Minecraft.method_2106(Minecraft.java:318)
	at net.minecraft.client.Minecraft.run(Minecraft.java:716)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_124.method_442(net.minecraft.class_31)" because "net.minecraft.class_124.field_468[this.field_753]" is null
	at net.minecraft.class_31.method_726(class_31.java:226)
	at modloader.ModLoader.AddName(ModLoader.java:365)
	at net.minecraft.AetherBlocks.<init>(AetherBlocks.java:106)
	at net.minecraft.mod_Aether.<init>(mod_Aether.java:105)
	... 15 more
```
	
</details>

**Comment by thecatcore** [comment]
Please use version 2.0.1 of Apron instead of 1.7.3+build

**Comment by OCsonic** [comment]
I'm currently trying to boot it up with the following mods
```
700-Aether-1.02_Client
Apron-2.0.1
mod-remapping-api-1.18.0
StationAPI-2.0-alpha.1.1
```
However it crashes with this trace
```
[07:51:14] [Minecraft main thread/ERROR] (Apron/ModLoader) Exception occured in ModLoader
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at modloader.ModLoader.addInternalMod(ModLoader.java:323) [apron-impl-2.0.1-16f524426015b3f1.jar:?]
	at modloader.ModLoader.readFromModFolder(ModLoader.java:1270) [apron-impl-2.0.1-16f524426015b3f1.jar:?]
	at modloader.ModLoader.init(ModLoader.java:790) [apron-impl-2.0.1-16f524426015b3f1.jar:?]
	at modloader.ModLoader.AddAllRenderers(ModLoader.java:222) [apron-impl-2.0.1-16f524426015b3f1.jar:?]
	at net.minecraft.class_578.handler$zck000$apron-impl$modloader$ctr(class_578.java:526) [client-intermediary.jar:?]
	at net.minecraft.class_578.<init>(class_578.java:75) [client-intermediary.jar:?]
	at net.minecraft.class_578.<clinit>(class_578.java:26) [client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.method_2106(Minecraft.java:318) [client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:716) [client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_124.method_442(net.minecraft.class_31)" because "net.minecraft.class_124.field_468[this.field_753]" is null
	at net.minecraft.class_31.method_726(class_31.java:226) ~[client-intermediary.jar:?]
	at modloader.ModLoader.AddName(ModLoader.java:365) [apron-impl-2.0.1-16f524426015b3f1.jar:?]
	at net.minecraft.AetherBlocks.<init>(AetherBlocks.java:106) ~[700-Aether-1.02_Client.zip:?]
	at net.minecraft.mod_Aether.<init>(mod_Aether.java:105) ~[700-Aether-1.02_Client.zip:?]
	... 15 more
```
(700 is prepended to the Aether mod's jar name because I sourced the jar from a b1.7.3 modpack I made and I wrote a tool that auto applies mods in numeric order for convenience. The jar itself is unmodified though)

For sanity sake I tested this on a fresh Babric instance, and I made sure it's actually on java 17. Is compatibility just not ready yet or am i doing something wrong?

**Comment by istupidgirl** [comment]
> Please use version 2.0.1 of Apron instead of 1.7.3+build

i was using 2.0.1. Github template defaulted it to 1.7.3+build.1 & i forgot to change it

**Comment by thecatcore** [comment]
Can you both send your full logs?
Apron-StAPI compat currently doesn't support adding dimensions from ML mods.

**Comment by istupidgirl** [comment]
> Can you both send your full logs? Apron-StAPI compat currently doesn't support adding dimensions from ML mods.

https://mclo.gs/Ur9Kb31

**Comment by OCsonic** [comment]
> Can you both send your full logs? Apron-StAPI compat currently doesn't support adding dimensions from ML mods.
https://mclo.gs/yFCNUCA

**Comment by fishiatee** [comment]
Running RML mods that adds new dimensions will not work with StAPI compat for now. But IIRC there was a functional port for StAPI, try looking it out.
